import type { Metadata } from 'next';
import { Montserrat, Rubik, Raleway } from 'next/font/google';
// eslint-disable-next-line import/order
import React from 'react';

import './globals.css';
import { Toaster } from 'sonner';

import { AuthProvider } from '@/providers/AuthProvider';
import QueryProvider from '@/providers/QueryProvider';

const montserrat = Montserrat({
   variable: '--font-montserrat',
   subsets: ['cyrillic', 'latin'],
});

const rubik = Rubik({
   variable: '--font-rubik',
   subsets: ['latin', 'cyrillic'],
});

const raleway = Raleway({
   variable: '--font-raleway',
   subsets: ['latin', 'cyrillic'],
});

export const metadata: Metadata = {
   title: 'Psylence',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body
            className={`${montserrat.variable} ${rubik.variable} ${raleway.variable} antialiased`}
         >
            <QueryProvider>
               <AuthProvider>{children}</AuthProvider>
            </QueryProvider>
            <Toaster />
         </body>
      </html>
   );
}
