import type { Metadata } from 'next';
import { Montserrat, Rubik, Raleway } from 'next/font/google';
import React from 'react';
import './globals.css';

const montserrat = Montserrat({
   variable: '--font-geist-sans',
   subsets: ['cyrillic', 'latin'],
});

const rubik = Rubik({
   variable: '--font-geist-mono',
   subsets: ['latin', 'cyrillic'],
});

const raleway = Raleway({
   variable: '--font-geist-mono',
   subsets: ['latin', 'cyrillic'],
});

export const metadata: Metadata = {
   title: 'Psylence',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body
            className={`${montserrat.variable} ${rubik.variable} ${raleway.variable} antialiased`}
         >
            {children}
         </body>
      </html>
   );
}
